Controllers/ExamController.cs
using Microsoft.AspNetCore.Mvc;
using Online_Exam.Models;
using System;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
public class ExamController : Controller
{

	private readonly OnlineExammDbContext db;

	public ExamController(OnlineExammDbContext context)
	{
        db = context;
	}

	public IActionResult Create()
	{
		var Name = HttpContext.Session.GetString("U_Email");
		if (string.IsNullOrEmpty(Name))
		{
			return RedirectToAction("Signin", "Login");
		}
		Exam exam = new Exam();
		return View(exam);
	}

	[HttpPost]
	public IActionResult Create(Exam exam)
	{

		string adminEmail = HttpContext.Session.GetString("U_Email");
		exam.Adminstration_Email = adminEmail;
		db.Exams.Add(exam);
		db.SaveChanges();
		HttpContext.Session.SetInt32("Exam_id", exam.Exam_id);
		return RedirectToAction("Create", "Question");
	}

	public IActionResult Index()
	{
        var Name = HttpContext.Session.GetString("U_Email");
        if (string.IsNullOrEmpty(Name))
        {
            return RedirectToAction("Signin", "Login");
        }
        string adminEmail = HttpContext.Session.GetString("U_Email");
		var exams = db.Exams
			.Where(e => e.Adminstration_Email == adminEmail)
			.ToList();

		return View(exams);
	}
    public IActionResult Details(int id)
    {
        var exam = db.Exams.FirstOrDefault(e => e.Exam_id == id);

        if (exam == null)
        {
            return NotFound();
        }

        return View(exam);
    }

    // Update Exam (GET)
    public IActionResult Edit(int id)
    {
        var exam = db.Exams.FirstOrDefault(e => e.Exam_id == id);

        if (exam == null)
        {
            return NotFound();
        }

        return View(exam);
    }

    [HttpPost]
    public IActionResult Edit(int id, Exam updatedExam)
    {
        if (id != updatedExam.Exam_id)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            var existingExam = db.Exams.Find(id);
            existingExam.Exam_title = updatedExam.Exam_title;
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        return View(updatedExam);
    }

    public IActionResult Delete(int id)
    {
        var exam = db.Exams.FirstOrDefault(e => e.Exam_id == id);

        if (exam == null)
        {
            return NotFound();
        }

        return View(exam);
    }

    [HttpPost, ActionName("Delete")]
    public IActionResult DeleteConfirmed(int id)
    {
        var exam = db.Exams.Find(id);

        if (exam == null)
        {
            return NotFound();
        }

        db.Exams.Remove(exam);
        db.SaveChanges();

        return RedirectToAction("Index");
    }
    [HttpPost]
    public IActionResult SaveExamCode(int examCode)
    {
        HttpContext.Session.SetInt32("ExamCode", examCode);
		return NoContent();
    }
    public IActionResult Finish()
	{
		HttpContext.Session.Remove("Exam_id");
		return RedirectToAction("Index", "Home");
	}
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Online_Exam.Models;
using System.Diagnostics;

namespace Online_Exam.Controllers
{
    public class HomeController : Controller
    {
        private readonly /*ILogger<HomeController>*/ OnlineExammDbContext _logger;

        public HomeController(/*ILogger<HomeController>*/OnlineExammDbContext logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            //var Name = HttpContext.Session.GetString("U_Email");
            //if (string.IsNullOrEmpty(Name))
            //{
            //    return RedirectToAction("Signin", "Login");
            //}
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PrintController.cs
using Microsoft.AspNetCore.Mvc;
using Online_Exam.Models;

namespace Online_Exam.Controllers
{
    public class PrintController : Controller
    {
        private readonly OnlineExammDbContext db;

        public PrintController(OnlineExammDbContext context)
        {
            db = context;
        }

        public IActionResult Index()
        {
            var x = HttpContext.Session.GetString("U_Email");
            if (string.IsNullOrEmpty(x))
            {
                return RedirectToAction("Signin", "Login");
            }
            var Name = HttpContext.Session.GetInt32("ExamCode").Value;
            ViewBag.mess = Name;
            List<Exam> ListExam = db.Exams.ToList();
            List<Questions> ListQuestions = db.Questions.ToList();
            List<Choices> ListChoices = db.Choices.ToList();
            PrintViewModel obViewModel = new PrintViewModel
            {
                ExamViewModel = ListExam,
                QuestionsViewModel = ListQuestions,
                ChoicesViewModel = ListChoices
            };

            return View(obViewModel);
        }
    }
}

Views/Home/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@{
    ViewData["Title"] = "Home Page";
}
<div class="text-center">
    <div class="home-page">
        <div class="landing">
            <div class="container">
                <div class="text">
                    <h1>Welcome To Our Website</h1>
                    <p>Here you can create and enter Exams and Forms <br>and share with others</p>
                </div>
            </div>
            <div class="choice">
                <form asp-controller="Exam" asp-action="Index">
                    <div class="box">
                        <div class="text">
                            <h2>Create Form</h2>
                            <p>You Can Create From step by step and share link</p>
                        </div>
                        <div class="foot">
                            <div class="create-btn">
                                <button>Create</button>
                            </div>
                        </div>
                    </div>
                </form>
                <div class="box-space"></div>
                <form asp-controller="Print" asp-action="Index" id="examForm">
                    <div class="box">
                        <div class="text">
                            <h2>Enter Form</h2>
                            <p>Please Enter Exam Code</p>
                        </div>
                        <div class="foot">
                            <input type="number" name="link" id="examCodeInput">
                            <div class="go-btn">
                                <button onclick="saveExamCode()">Go</button>
                            </div>
                        </div>
                    </div>
                </form>

            </div>
        </div>
    </div>
</div>
<script>
    function saveExamCode() {
        var examCode = document.getElementById("examCodeInput").value;
        $.post("/Exam/SaveExamCode", { examCode: examCode }, function (data) {
            console.log(data);
        });
    }
</script>
<style>
    * {
        -webkit-box-sizing: border-box;
        -moz-box-sizing: border-box;
        box-sizing: border-box;
    }

    body {
        font-family: 'Cairo', sans-serif;
        background-color: #eee;
    }

    :root {
        --main-color: #003971;
        --main-color-alt: #1787e0;
        --main-transition: 0.3s;
        --main--padding-top: 108px;
        --main--padding-bottom: 108px;
        --section-background: #ececec;
    }

    html {
        scroll-behavior: smooth;
    }

    ul {
        list-style: none;
        padding: 0;
        margin: 0;
    }

    .container {
        padding-right: 15px;
        padding-left: 15px;
        margin-right: auto;
        margin-left: auto;
    }

    header {
        position: relative;
        background-color: white;
        -webkit-box-shadow: 0 0 10px #ddd;
        -moz-box-shadow: 0 0 10px #ddd;
        box-shadow: 0 0 10px #ddd;
        margin-top: -5px;
    }


    .landing {
        position: relative;
        top: -40px;
    }

        .landing::before {
            content: "";
            position: absolute;
            width: 100%;
            height: 100%;
            top: -30px;
            left: 0;
            background-color: #ececec;
            z-index: -1;
        }

        .landing > .container {
            min-height: 500px;
            display: flex;
            justify-content: center;
            align-items: center;
            padding-bottom: -50px;
            margin-bottom: -250px;
        }

        .landing .text {
            flex: 1;
            margin-top: -200px;
            text-align: center;
        }

            .landing .text h1 {
                font-size: 40px;
                margin: 0;
                letter-spacing: -2;
            }

            .landing .text p {
                line-height: 1.7;
                color: #666;
                font-size: 23px;
                margin: 5px 0 -20px 0;
            }

        .landing .choice {
            display: grid;
            grid-template-columns: repeat(100px, 1fr);
            gap: 20px;
            justify-content: center;
            align-items: center;
            margin-left: 50px;
            margin-right: 50px;
        }

    .choice .box {
        border-radius: 15px;
        -webkit-border-radius: 15px;
        -moz-border-radius: 15px;
        -ms-border-radius: 15px;
        -o-border-radius: 15px;
        box-shadow: 0 0 10px #ddd;
        transition: transform var(--main-transition), box-shadow var(--main-transition);
        -webkit-transition: transform var(--main-transition), box-shadow var(--main-transition);
        -moz-transition: transform var(--main-transition), box-shadow var(--main-transition);
        -ms-transition: transform var(--main-transition), box-shadow var(--main-transition);
        -o-transition: transform var(--main-transition), box-shadow var(--main-transition);
        background-color: white;
        padding: 30px 70px 10px;
    }

        .choice .box > div {
            margin: 20px;
            position: relative;
            background-color: white;
        }

        .choice .box:hover {
            transform: translateY(-10px);
            -webkit-transform: translateY(-10px);
            -moz-transform: translateY(-10px);
            -ms-transform: translateY(-10px);
            -o-transform: translateY(-10px);
            box-shadow: 0 0 20px #ccc;
        }

        .choice .box h2 {
            color: var(--main-color);
        }

        .choice .box .foot {
            margin: 40px 70px;
            padding: 0 15px;
            align-items: center;
        }

            .choice .box .foot a {
                text-decoration: none;
                font-size: 20px;
                color: black;
                font-weight: bold;
            }

        .choice .box .go-btn {
            display: flex;
            justify-content: center;
            align-items: center;
            margin: 20px 0 0 30px;
            background-color: var(--main-color);
            width: 100px;
            height: 30px;
        }

        .choice .box .foot input {
            margin: 0 0 0 -10px;
            width: 200px;
            border: 2px solid black;
        }

        .choice .box .foot a {
            text-decoration: none;
            font-size: 20px;
            color: black;
            font-weight: bold;
        }

        .choice .box .create-btn {
            display: flex;
            justify-content: center;
            align-items: center;
            margin: 20px 0 0 30px;
            background-color: var(--main-color);
            width: 100px;
            height: 30px;
        }

            .choice .box .create-btn button,
            .choice .box .go-btn button {
                background-color: #003971;
                color: white;
                width: 100%;
                height: 100%;
                border: none;
                cursor: pointer;
            }

        .choice .box .create-btn,
        .choice .box .go-btn {
            display: flex;
            justify-content: center;
            align-items: center;
            margin: 20px 0 0 150px;
        }
</style>