Models/Choices.cs
using Online_Exam.Models;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Online_Exam.Models
{
    public class Choices
    {
        [Key, Column(Order = 0)]
        [Required]
        // [ForeignKey("Questions")]
        public int Exam_id { get; set; }

        [Key, Column(Order = 1)]
        [Required]
        // [ForeignKey("Questions")]
        public int Question_id { get; set; }

        [Key, Column(Order = 2)]
        [Required]
        public string Choice_text { get; set; }

        public bool Is_correct { get; set; }


        [ForeignKey("Exam_id,Question_id")]
        public virtual Questions Questions { get; set; } = null!;
    }
}

Controllers/ChoicesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Online_Exam.Models;
using System;
using System.Linq;
public class ChoicesController : Controller
{
	private readonly OnlineExammDbContext _context;

	public ChoicesController(OnlineExammDbContext context)
	{
		_context = context;
	}

	// Index action to display all choices
	public IActionResult Index()
	{
		int examId = HttpContext.Session.GetInt32("Exam_id").Value;
		int questionId = HttpContext.Session.GetInt32("Question_id").Value;

		var choices = _context.Choices
			.Where(c => c.Exam_id == examId && c.Question_id == questionId)
			.ToList();

		return View(choices);
	}

	// Create action to add a new choice
	public IActionResult Create()
	{
		var Name = HttpContext.Session.GetString("U_Email");
		var examId = HttpContext.Session.GetString("Exam_id");
		var questionId = HttpContext.Session.GetString("Question_id");
		if (string.IsNullOrEmpty(Name))
		{
			return RedirectToAction("Signin", "Login");
		}
		if (examId == null)
		{
			return RedirectToAction("Index", "Home");
		}
		if (questionId == null)
		{
			return RedirectToAction("Index", "Home");
		}
		Choices c = new Choices();
		return View();
	}

	[HttpPost]
	[ValidateAntiForgeryToken]
	public IActionResult Create(Choices choice)
	{
		int examId = HttpContext.Session.GetInt32("Exam_id").Value;
		int questionId = HttpContext.Session.GetInt32("Question_id").Value;
		choice.Exam_id = examId;
		choice.Question_id = questionId;
		_context.Choices.Add(choice);
		_context.SaveChanges();
		return RedirectToAction("Index");
	}

	// Edit action to update an existing choice
	//public IActionResult Edit(int id)
	//{
	//    var choice = _context.Choices.Find(id);

	//    if (choice == null)
	//    {
	//        return NotFound();
	//    }

	//    return View(choice);
	//}

	/*[HttpPost]
    [ValidateAntiForgeryToken]*/
	//public IActionResult Edit(int id, Choices choice)
	//{
	//    if (id != choice.Choice_id)
	//    {
	//        return NotFound();
	//    }

	//    if (ModelState.IsValid)
	//    {
	//        _context.Entry(choice).State = EntityState.Modified;
	//        _context.SaveChanges();
	//        return RedirectToAction(nameof(Index));
	//    }

	//    return View(choice);
	//}

	// Details action to view details of a choice
	//public IActionResult Details(int id)
	//{
	//    var choice = _context.Choices.Find(id);

	//    if (choice == null)
	//    {
	//        return NotFound();
	//    }

	//    return View(choice);
	//}

	//// Delete action to delete a choice
	//public IActionResult Delete(int id)
	//{
	//    var choice = _context.Choices.Find(id);

	//    if (choice == null)
	//    {
	//        return NotFound();
	//    }

	//    return View(choice);
	//}

	//[HttpPost, ActionName("Delete")]
	//[ValidateAntiForgeryToken]
	//public IActionResult DeleteConfirmed(int id)
	//{
	//    var choice = _context.Choices.Find(id);
	//    _context.Choices.Remove(choice);
	//    _context.SaveChanges();
	//    return RedirectToAction(nameof(Index));
	//}
}

Controllers/QuestionController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Online_Exam.Models;
using System;
using System.Linq;

public class QuestionController : Controller
{
	private readonly OnlineExammDbContext _context;

	public QuestionController(OnlineExammDbContext context)
	{
		_context = context;
	}
	// GET: Questions/Create
	public IActionResult Create()
	{
		var Name = HttpContext.Session.GetString("U_Email");
		var examId = HttpContext.Session.GetInt32("Exam_id");
		if (string.IsNullOrEmpty(Name))
		{
			return RedirectToAction("Signin", "Login");
		}
		if (examId == null)
		{
			return RedirectToAction("Index", "Home");
		}
		Questions q = new Questions();
		return View();
	}
	// POST: Questions/Create
	[HttpPost]
	//[ValidateAntiForgeryToken]
	public IActionResult Create(Questions question)
	{
		//question.Exam_id = HttpContext.Session.GetInt32("Exam_id").Value;
		int examId = HttpContext.Session.GetInt32("Exam_id").Value;
		question.Exam_id = examId;
		_context.Add(question);
		_context.SaveChanges();
		HttpContext.Session.SetInt32("Question_id", question.Question_id);
		return RedirectToAction("Create", "Choices"); // Adjust the action and controller accordingly
													  //HttpContext.Session.SetInt32("Question_id", question.Question_id);

	}
	// GET: Questions/Edit/5
	//public IActionResult Edit(int? id)
	//{
	//    if (id == null)
	//    {
	//        return NotFound();
	//    }

	//    Questions question = _context.Questions.Find(id);

	//    if (question == null)
	//    {
	//        return NotFound();
	//    }

	//    return View(question);
	//}

	// POST: Questions/Edit/5
	//[HttpPost]
	//[ValidateAntiForgeryToken]
	//public IActionResult Edit(int id, Questions question)
	//{
	//    if (id != question.Question_id)
	//    {
	//        return NotFound();
	//    }

	//    if (ModelState.IsValid)
	//    {
	//        try
	//        {
	//            _context.Entry(question).State = EntityState.Modified;
	//            _context.SaveChanges();
	//        }
	//        catch (DbUpdateConcurrencyException)
	//        {
	//            if (!QuestionExists(question.Question_id))
	//            {
	//                return NotFound();
	//            }
	//            else
	//            {
	//                throw;
	//            }
	//        }

	//        // Redirect to wherever you need to go next
	//        return RedirectToAction("Index", "Home"); // Adjust the action and controller accordingly
	//    }

	//    return View(question);
	//}

	//// GET: Questions/Delete/5
	//public IActionResult Delete(int? id)
	//{
	//    if (id == null)
	//    {
	//        return NotFound();
	//    }

	//    Questions question = _context.Questions.Find(id);

	//    if (question == null)
	//    {
	//        return NotFound();
	//    }

	//    return View(question);
	//}

	//// POST: Questions/Delete/5
	//[HttpPost, ActionName("Delete")]
	//[ValidateAntiForgeryToken]
	//public IActionResult DeleteConfirmed(int id)
	//{
	//    Questions question = _context.Questions.Find(id);
	//    _context.Questions.Remove(question);
	//    _context.SaveChanges();

	//    // Redirect to wherever you need to go next
	//    return RedirectToAction("Index", "Home"); // Adjust the action and controller accordingly
	//}
	public IActionResult Finish()
	{
		HttpContext.Session.Remove("Question_id");
		return RedirectToAction("Create");
	}

}

Views/Choices/Create.cshtml
@model Online_Exam.Models.Choices

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    /* Add custom styles here */
    body {
        background-color: #f8f9fa;
    }

    .container {
        margin-top: 50px;
    }

    h1 {
        color: #007bff;
    }

    .form-group {
        margin-bottom: 20px;
    }

    /* Add more styles as needed */
</style>

<div class="container">
    <h1>Create</h1>

    <h4>Choices</h4>
    <hr />

    <div class="row">
        <div class="col-md-6">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group">
                    <label for="Choice_text" class="control-label">
                        <i class="fas fa-pencil-alt"></i> Choice Text
                    </label>
                    <input asp-for="Choice_text" class="form-control" />
                    <span asp-validation-for="Choice_text" class="text-danger"></span>
                </div>

                <div class="form-group form-check">
                    <label class="form-check-label">
                        <input class="form-check-input" asp-for="Is_correct" />
                        @Html.DisplayNameFor(model => model.Is_correct)
                    </label>
                </div>

                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>

            <form asp-controller="Question" asp-action="Finish">
                <div class="form-group">
                    <input type="submit" value="Finish" class="btn btn-success" />
                </div>
            </form>
        </div>
    </div>
@* 
    <div>
        <a asp-action="Index" class="btn btn-secondary">Back to List</a>
    </div> *@
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Choices/Index.cshtml
@model IEnumerable<Online_Exam.Models.Choices>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Is_correct)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Choice_text)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Is_correct)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Choice_text)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                </td>
            </tr>
        }
    </tbody>
</table>